---
title: Tidying data
author: R package build
date: '2022-02-14'
slug: tidying-data
categories: []
tags: []
---

## Import file from GitHub

## Call libraries
```{r}
library(tidyverse)
```

```{r}
url6 <- 'https://raw.githubusercontent.com/gnunez2020/tidyverse/main/purchases.csv'
purchases <- read_csv(url6)
names(purchases)
```

## Pivot Longer

```{r}
#pivot_longer(data, cols, names_to = "name", values_to = "value")
```

```{r}
 #purchases <- customers %>%
 # pivot_longer(
 #   cols = item_1:item_3,  # variables item_1 to item_3
 #   names_to = "item_no",  # column names -> new column called item_no
 #   values_to = "item"     # values in columns -> new column called item
  #  )
purchases
```

```{r}
url7 <- 'https://raw.githubusercontent.com/gnunez2020/tidyverse/main/prices.csv'
prices <- read_csv(url7)
names(prices)
```

```{r}
purchases %>%
  left_join(prices)
```

```{r}
# purchases %>%
#  pivot_wider(
#    names_from = item_no,
#    values_from = item
#  )
```

## Case study: Approval rating of Donald Trump

```{r}
url8 <- 'https://raw.githubusercontent.com/gnunez2020/tidyverse/main/trump.csv'
trump <- read_csv(url8)
names(trump)
```

```{r}
# Pivot
trump_longer <- trump %>%
  pivot_longer(
    cols = c(approval, disapproval),
    names_to = "rating_type",
    values_to = "rating_value"
  )
trump_longer
```

```{r}
# Plot
ggplot(trump_longer, 
       aes(x = date, y = rating_value, 
           color = rating_type, group = rating_type)) +
  geom_line() +
  facet_wrap(~ subgroup) +
  scale_color_manual(values = c("darkgreen", "orange")) + 
  labs( 
    x = "Date", y = "Rating", 
    color = NULL, 
    title = "How (un)popular is Donald Trump?", 
    subtitle = "Estimates based on polls of all adults and polls of likely/registered voters", 
    caption = "Source: FiveThirtyEight modeling estimates" 
  ) + 
  theme_minimal() +
  theme(legend.position = "bottom")
```

