---
title: Recoding data
author: R package build
date: '2022-02-22'
slug: recoding-data
categories: []
tags: []
---
```{r}
library(tidyverse)
```

# Case study: Religion and income
```{r}
library(readxl)
rel_inc <- read_csv("https://raw.githubusercontent.com/gnunez2020/tidyverse/main/relig-income.csv")
```

## Rename columns
```{r}
rel_inc %>%
  rename( 
    religion = `Religious tradition`, 
    n = `Sample Size` 
  )
```
>
If we want a new variable called income with levels such as "Less than $30,000", "$30,000-$49,999", ... etc. which function should we use?

## Pivot longer
```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer( 
    cols = -c(religion, n),   # all but religion and n 
    names_to = "income",  
    values_to = "proportion" 
  )
```

## Calculate frequencies
```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion"
  ) 
```

## Save data
```{r}
rel_inc_long <- rel_inc %>% 
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion"
  ) 
```

## Barplot
```{r}
#ggplot(rel_inc_long, aes(y = religion, x = frequency)) +
  #geom_col()
```

## Recode religion
```{r}
rel_inc_long <- rel_inc_long %>%
  mutate(religion = case_when(
    religion == "Evangelical Protestant"           ~ "Ev. Protestant",
    religion == "Historically Black Protestant"    ~ "Hist. Black Protestant",
    religion == 'Unaffiliated (religious "nones")' ~ "Unaffiliated",
    TRUE                                           ~ religion
  ))
rel_inc_long
```

## Reverse religion order
```{r}
rel_inc_long <- rel_inc_long %>%
  mutate(religion = fct_rev(religion))
```

## Add income
>```{r}
 #ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) + 
  #geom_col()
```

## Fill bars
```{r}
#ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  #geom_col(position = "fill")
```

## Change colors
```{r}
#ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  #geom_col(position = "fill") +
  #scale_fill_viridis_d()
```

## Change theme
```{r}
#ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  #geom_col(position = "fill") +
  #scale_fill_viridis_d() +
  #theme_minimal()
```

## Move legend to the bottom
```{r}
#ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  #geom_col(position = "fill") +
 # scale_fill_viridis_d() +
  #theme_minimal() +
  #theme(legend.position = "bottom")
```

## Legend adjustments
```{r}
#ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  #geom_col(position = "fill") +
  #scale_fill_viridis_d() +
  #theme_minimal() +
  #theme(legend.position = "bottom") +
  #guides(fill = guide_legend(nrow = 2, byrow = TRUE))
```

## Fix labels



