---
title: Visualizing Categorical Data
author: R package build
date: '2022-02-09'
slug: visualizing-categorical-data
categories:
  - R
  - GGPLOT2
tags:
  - GGPLOT2
  - OpenIntro
---

## Call Libraies
```{r}
library(tidyverse)
library(openintro)
loans <- loans_full_schema %>%
  select(loan_amount, interest_rate, term, grade, 
         state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```
## Bar Plot
```{r}
ggplot(loans, aes(x = homeownership)) +
  geom_bar()
```

## Segmented Bar Plot
```{r}
ggplot(loans, aes(x = homeownership, 
                  fill = grade)) +
  geom_bar()
```
```{r}
ggplot(loans, aes(x = homeownership, fill = grade)) +
  geom_bar(position = "fill")
```

## Customized Flipped Bar Plot 
```{r}
ggplot(loans, aes(y = homeownership,
                  fill = grade)) +
  geom_bar(position = "fill") +
  labs(
    x = "Proportion",
    y = "Homeownership",
    fill = "Grade",
    title = "Grades of Lending Club loans",
    subtitle = "and homeownership of lendee"
  )
```

## Violin Plot
```{r}
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
  geom_violin()
```

##Ridge Plot
```{r}
library(ggridges)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) + 
  geom_density_ridges(alpha = 0.5)
```

